import { Open_Sans } from "next/font/google";
import { ReactNode } from "react";
import Navbar from "./(shared)/Navbar";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "GPT Blog",
  description: "Generated by ChatGPT",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
